apiVersion: v1
kind: Namespace
metadata:
  name: kube-demo-lb

---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replacaset-nginx-systems
  namespace: kube-demo-lb
  labels:
    app: replacaset-nginx-systems
    type: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: replacaset-nginx-systems
  template:
    metadata:
      labels:
        app: replacaset-nginx-systems
        type: frontend
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: replacaset-nginx-systems
  namespace: kube-demo-lb
spec:
  selector:
    app: replacaset-nginx-systems
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
