apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp-product
  template:
    metadata:
      labels:
        app: myapp-product
    spec:
      containers:
      - name: nginx-container
        image: nginx
