apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  type: front-end
spec:
  selector:
    matchLabels:
      app: myapp-product
  template:
    metadata:
      labels:
        app: myapp-product
    spec:
      containers:
      - name: nginx-container
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
replicas: 3
selector:
  matchLabels:
    type: front-end
