apiVersion: v1
kind: ReplicationController
metadata:
  name: replication-monitor-systems
  labels:
    name: replication-monitor-systems
spec:
  template:
    metadata:
      name: pod-monitor-systems
      labels:
        name: pod-monitor-systems
    spec:
      containers:
      - name: prometheus
        image: ubuntu/prometheus
      - name: grafana
        image: grafana/grafana
          
  replicas: 3