apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp
  labels:
    name: myapp-pod-monitor
spec:
  template:
    metadata:
      name: myapp
      labels:
        name: myapp-pod-monitor
    spec:
      containers:
      - name: prometheus
        image: ubuntu/prometheus
      - name: grafana
        image: grafana/grafana
          
  replicas: 3