apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-controller
  labels:
      app: myapp
      type: frontend
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: frontend
    spec:
      containers:
      - name: nginx-container
        images: nginx

