apiVersion: v1
kind: ReplicaSet
metadata:
  name: replacaset-nginx-systems
  labels:
      app: replacaset-nginx-systems
      type: frontend
spec:
  template:
      metadata:
        name: pod-service-nginx
        labels:
          name: pod-service-nginx
      spec:
        containers:
        - name: nginx
          image: nginx
