apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replacaset-nginx-systems
  labels:
      app: replacaset-nginx-systems
      type: frontend
spec:
  template:
      metadata:
        name: pod-service-nginx
        labels:
          name: pod-service-nginx
      spec:
        containers:
        - name: nginx
          image: nginx

  replicas: 3
  selector:
      matchLabels:
        name: pod-service-nginx
