apiVersion: v1
kind: Service
metadata:
  name: myapp-service-replicaset
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008
  selector:
    app: replacaset-nginx-systems
    type: front-end